### PR TITLE
Implementing Clipped Convex functions, some other improvements

### PR DESCRIPTION
**Pull request by angeris**
This is just a continuation of #7; so far it is good (though may be missing some tests). Doing the PR to allow for further review. 

Additionally, the RANSAC test is failing due to a singular matrix exception on my machine. I'm not sure how we should proceed here: should we (a) use any of the possible right-inverses? (In a similar way to the pseudoinverse?) Or (b) use a `damped'/slightly regularized solution when an exception is caught? Note that (a) ≈ (b), but I'm not sure which is better at the moment. (I would opt for (b), but we can do either way!)

### CODE REVIEW

**Comment by jbytecode** [comment]
@tantei3 could you kindly please handle this?

**Comment by jbytecode** [comment]
@angeris you can check the estimated betas in your tests and it is not necessary your algorithm to find correct outliers at all.

**Comment by angeris** [comment]
@jbytecode Ok, just added the comparison. Note that the test for RANSAC is still failing, so I'm not sure this is ready to be merged (see the top comment).

**Comment by jbytecode** [comment]
> @jbytecode Ok, just added the comparison. Note that the test for RANSAC is still failing, so I'm not sure this is ready to be merged (see the top comment).

is RANSAC only the problem? did you change any code related to it? if your answer is no, you can finalize because it may a problem with your machine or setup.

**Comment by angeris** [comment]
The only change was with OLS; I changed the explicit `pinv` (which is very expensive to compute) to a QR factorization, which is much less so. The problem is that `pinv(A)` is defined for all `A`, while `qr(A)`, as implemented in the current linear algebra libraries, is only defined for full rank `A`. We can fix this in either of the ways I mention above.

I can also decouple the changes and we can talk about them separately as well! Whatever is easier :)

**Comment by jbytecode** [comment]
> The only change was with OLS; I changed the explicit `pinv` (which is very expensive to compute) to a QR factorization, which is much less so. The problem is that `pinv(A)` is defined for all `A`, while `qr(A)`, as implemented in the current linear algebra libraries, is only defined for full rank `A`. We can fix this in either of the ways I mention above.
> 
> I can also decouple the changes and we can talk about them separately as well! Whatever is easier :)

okay please get pinv() again. It is preventing errors in Ransac. I am waiting for the pull request.

**Comment by jbytecode** [comment]
@angeris we can add a method for qr later for this.

**Comment by angeris** [comment]
Ok, I actually just changed it to pivoted QR which does the required check. Now works with RANSAC.

**Comment by sbarratt** [comment]
Well done @angeris !

**Comment by jbytecode** [comment]
> Well done @angeris !
> 
> Mentioned here: https://github.com/cvxgrp/sccf/blob/master/README.md#notes

I manually added to it. Thank you all

**Comment by angeris** [comment]
Thanks! Let me know if other documentation needs to be updated.

**Comment by jbytecode** [comment]
> Thanks! Let me know if other documentation needs to be updated.

Citation is enough. Documentation is okay, well done, thank you

**Pull request merged**
